modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "AGPL-3.0-or-later"

[[mods]]
modId = "tameable_rabbits"
version = "${version}"
displayName = "Tameable Rabbits"
authors = "tired9494"
description = '''

'''
logoFile = "assets/tameable_rabbits/icon.png"

[[dependencies.tameable_rabbits]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.tameable_rabbits]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.tameable_rabbits]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "tameable_rabbits.mixins.json"
